---
title: Book
author: Reedeeng

url: https://reedeeng.github.io/book
baseurl: /book

permalink: pretty

collections:
  posts:
    output: false
  chapter-1:
    output: true
  chapter-2:
    output: true
