---
title: Book
author: Reedeeng

url: https://reedeeng.github.io/book
baseurl: /book

permalink: pretty

collections:
  chapter-1:
    label: chapter one
    output: true
  chapter-2:
    output: true
  chapter-3:
    output: true
---
