---
title: Book
author: Reedeeng

url: https://reedeeng.github.io/book
baseurl: /book

permalink: pretty

collections:
  chapter-1:
    title: chapter one
    output: true
  chapter-2:
    title: chapter two
    output: true
  chapter-3:
    title: chapter three
    output: true
---
